resources:
- name: RobiNino_gradle_example_pipelines_gitResource
  type: GitRepo
  configuration:
    path: RobiNino/gradle-example-pipelines
    gitProvider: github_RobiNino_gradle_example_pipelines_integration
    buildOn:
      pullRequestCreate: true
    branches:
      include: main
pipelines:
- name: RobiNino_gradle_example_pipelines_pipeline
  configuration:
    runtime:
      type: image
      image:
        custom:
          name: releases-docker.jfrog.io/jfrog/jfrog-cli-full
          tag: latest
  steps:
  - name: Build
    type: Bash
    configuration:
      inputResources:
      - name: RobiNino_gradle_example_pipelines_gitResource
      integrations:
      - name: rt_RobiNino_gradle_example_pipelines_integration
    execution:
      onExecute:
      - cd $res_RobiNino_gradle_example_pipelines_gitResource_resourcePath
      - export CI=true
      - export JFROG_CLI_BUILD_NAME=gradle-example-pipelines-main
      - export JFROG_CLI_BUILD_NUMBER=$run_number
      - export JFROG_CLI_BUILD_URL=$step_url
      - export JFROG_BUILD_RESULTS=PASS
      - jfrog c add RobiNino_gradle_example_pipelines_serverId --artifactory-url $int_rt_RobiNino_gradle_example_pipelines_integration_url
        --user $int_rt_RobiNino_gradle_example_pipelines_integration_user --apikey
        $int_rt_RobiNino_gradle_example_pipelines_integration_apikey --enc-password=false
      - jfrog rt gradle-config --server-id-resolve RobiNino_gradle_example_pipelines_serverId
        --repo-resolve gradle-virtual
      - jfrog rt gradle clean artifactoryPublish
      - jfrog rt bag
      - jfrog rt bce
      - jfrog rt bp
      onComplete:
      - update_commit_status RobiNino_gradle_example_pipelines_gitResource
      onFailure:
      - export JFROG_BUILD_RESULTS=FAIL
      - jfrog rt bce
      - jfrog rt bp
